# Generated by Django 3.2 on 2021-04-21 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist_url',
        ),
        migrations.RemoveField(
            model_name='track',
            name='album_url',
        ),
        migrations.RemoveField(
            model_name='track',
            name='artist_url',
        ),
        migrations.AddField(
            model_name='album',
            name='artist_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='music.artist'),
        ),
        migrations.AddField(
            model_name='track',
            name='album_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='music.album'),
        ),
        migrations.AddField(
            model_name='track',
            name='artist_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='music.artist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.CharField(max_length=50),
        ),
    ]
