# Generated by Django 3.2 on 2021-04-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20210421_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='albums',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='artist',
            name='tracks',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='artist',
            name='url',
            field=models.CharField(default='', max_length=50),
        ),
    ]
