# Generated by Django 3.2 on 2021-04-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20210421_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='album',
            name='tracks',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='album',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='artist',
            name='albums',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='artist',
            name='tracks',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='artist',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='track',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
