# Generated by Django 3.2 on 2021-04-23 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20210421_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist',
            new_name='artist_url',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='tracks',
            new_name='tracks_url',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='albums',
            new_name='albums_url',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='tracks',
            new_name='tracks_url',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='album',
            new_name='album_url',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='artist',
            new_name='artist_url',
        ),
    ]
