# Generated by Django 3.2 on 2021-04-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_rename_artist_album_artist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.FloatField(),
        ),
    ]
